=== onap/sdc/openecomp-be/backend/openecomp-sdc-vendor-software-product-manager/src/test/resources/quesionnaire/schema/componentQuestionnaire.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "general": {
      "type": "object",
      "properties": {
        "hypervisor": {
          "type": "object",
          "properties": {
            "hypervisor": {
              "type": "string",
              "enum": [
                "KVM",
                "VMWare ESXi"
              ],
              "default": "KVM"
            },
            "drivers": {
              "type": "string",
              "maxLength": 300,
              "pattern": "^[A-Za-z0-9_,-]*$"
            },
            "containerFeaturesDescription": {
              "type": "string",
              "maxLength": 1000,
              "pattern": "^[A-Za-z0-9_, -]*$"
            }
          },
          "additionalProperties": false
        },
        "image": {
          "type": "object",
          "properties": {
            "format": {
              "type": "string",
              "enum": [
                "aki",
                "ami",
                "ari",
                "iso",
                "qcow2",
                "raw",
                "vdi",
                "vhd",
                "vmdk"
              ],
              "default": "qcow2"
            },
            "providedBy": {
              "type": "string",
              "enum": [
                "Vendor"
              ],
              "default": "Vendor"
            },
            "bootDiskSizePerVM": {
              "type": "number",
              "maximum": 100
            },
            "ephemeralDiskSizePerVM": {
              "type": "number",
              "maximum": 400
            }
          },
          "additionalProperties": false
        },
        "recovery": {
          "type": "object",
          "properties": {
            "pointObjective": {
              "type": "number",
              "minimum": 0,
              "exclusiveMinimum": true,
              "maximum": 15,
              "exclusiveMaximum ": true
            },
            "timeObjective": {
              "type": "number",
              "minimum": 0,
              "exclusiveMinimum": true,
              "maximum": 300,
              "exclusiveMaximum ": true
            },
            "vmProcessFailuresHandling": {
              "type": "string"
            }
          },
          "additionalProperties": false
        },
        "dnsConfiguration": {
          "type": "string"
        },
        "vmCloneUsage": {
          "type": "string",
          "maximum": 300
        }
      },
      "additionalProperties": false
    },
    "compute": {
      "type": "object",
      "properties": {
        "vmSizing": {
          "type": "object",
          "properties": {
            "numOfCPUs": {
              "type": "number",
              "minimum": 0,
              "exclusiveMinimum": true,
              "maximum": 16,
              "default": 2
            },
            "fileSystemSizeGB": {
              "type": "number",
              "minimum": 0,
              "exclusiveMinimum": true,
              "default": 5
            },
            "persistentStorageVolumeSize": {
              "type": "number",
              "minimum": 0,
              "exclusiveMinimum": true
            },
            "IOOperationsPerSec": {
              "type": "number",
              "minimum": 0,
              "exclusiveMinimum": true
            }
          },
          "additionalProperties": false
        },
        "numOfVMs": {
          "type": "object",
          "properties": {
            "minimum": {
              "type": "number",
              "minimum": 0,
              "exclusiveMinimum": true,
              "maximum": 100
            },
            "maximum": {
              "type": "number",
              "minimum": 0,
              "exclusiveMinimum": true,
              "maximum": 100
            },
            "CpuOverSubscriptionRatio": {
              "type": "string",
              "enum": [
                "1:1",
                "4:1",
                "16:1"
              ],
              "default": "4:1"
            },
            "MemoryRAM": {
              "type": "string",
              "enum": [
                "2 GB",
                "4 GB",
                "8 GB"
              ],
              "default": "2 GB"
            }
          },
          "additionalProperties": false
        },
        "guestOS": {
          "type": "object",
          "properties": {
            "name": {
              "type": "string",
              "maxLength": 50
            },
            "bitSize": {
              "type": "number",
              "enum": [
                64,
                32
              ],
              "default": 64
            },
            "tools": {
              "type": "string"
            }
          },
          "additionalProperties": false
        }
      },
      "additionalProperties": false
    },
    "highAvailabilityAndLoadBalancing": {
      "type": "object",
      "properties": {
        "failureLoadDistribution": {
          "type": "string",
          "maxLength": 1000
        },
        "nkModelImplementation": {
          "type": "string",
          "maxLength": 1000
        },
        "architectureChoice": {
          "type": "string",
          "maxLength": 1000
        },
        "slaRequirements": {
          "type": "string",
          "maxLength": 1000
        },
        "horizontalScaling": {
          "type": "string",
          "maxLength": 1000
        },
        "loadDistributionMechanism": {
          "type": "string",
          "maxLength": 1000
        }
      },
      "additionalProperties": false
    },
    "network": {
      "type": "object",
      "properties": {
        "networkCapacity": {
          "type": "object",
          "properties": {
            "protocolWithHighestTrafficProfileAcrossAllNICs": {
              "type": "string",
              "enum": [
                "",
                "TCP",
                "UDP",
                "SCTP",
                "IPsec"
              ],
              "default": ""
            },
            "networkTransactionsPerSecond": {
              "type": "number"
            }
          },
          "additionalProperties": false
        }
      },
      "additionalProperties": false
    },
    "storage": {
      "type": "object",
      "properties": {
        "backup": {
          "type": "object",
          "properties": {
            "backupType": {
              "type": "string",
              "enum": [
                "On Site",
                "Off Site"
              ],
              "default": "On Site"
            },
            "backupStorageSize": {
              "type": "number"
            },
            "backupSolution": {
              "type": "string"
            },
            "backupNIC": {
              "type": "string",
              "enum": [
                ""
              ],
              "default": ""
            }
          },
          "additionalProperties": false
        },
        "snapshotBackup": {
          "type": "object",
          "properties": {
            "snapshotFrequency": {
              "type": "number",
              "default": 24,
              "minimum": 1,
              "exclusiveMinimum": true
            }
          },
          "additionalProperties": false
        },
        "logBackup": {
          "type": "object",
          "properties": {
            "sizeOfLogFiles": {
              "type": "number",
              "maximum": 5,
              "exclusiveMaximum": true
            },
            "logBackupFrequency": {
              "type": "number",
              "maximum": 4,
              "exclusiveMaximum": true
            },
            "logRetentionPeriod": {
              "type": "number",
              "maximum": 15,
              "exclusiveMaximum": true
            },
            "logFileLocation": {
              "type": "string",
              "maxLength": 300
            }
          },
          "additionalProperties": false
        }
      },
      "additionalProperties": false
    }
  },
  "additionalProperties": false
}

=== onap/sdc/openecomp-be/backend/openecomp-sdc-vendor-software-product-manager/src/test/resources/quesionnaire/invalidComponent.json
{
  "general": {
    "hypervisor": {
      "hypervisor": "KVM",
      "containerFeaturesDescription": "Nn8XhahKjo,FapqJ4Ale11LkO-f3,TlCJ2d0S Q B1w0JJwZgWo MeqEk85utsaM tdM33ZmAiAKp__c_PRBt_5-24gBU21unWme",
      "drivers": ",Lz-m3R7iwRREmjBA3Ss6b0K8YBcH4SS66UJSG8OGTlaMs6Be"
    },
    "image": {
      "ephemeralDiskSizePerVM": 8,
      "format": "iso",
      "bootDiskSizePerVM": 100,
      "providedBy": "Vendor"
    },
    "dnsConfiguration": "dolore adipisicing proident aute amet",
    "recovery": {
      "vmProcessFailuresHandling": "in ad est ut",
      "pointObjective": 20
    }
  },
  "network": {},
  "highAvailabilityAndLoadBalancing": {
    "architectureChoice": "nostrud eu culpa velit Lorem",
    "slaRequirements": "est esse Excepteur eu",
    "failureLoadDistribution": "velit reprehenderit aute dolor in",
    "loadDistributionMechanism": "quis fugiat veniam cillum"
  },
  "storage": {
    "backup": {
      "backupType": "On Site",
      "backupStorageSize": 9,
      "backupSolution": "fugiat tempor"
    }
  }
}
